#!/bin/bash

##script to detect bluetooth at boot and launch blueman if found.


## grep for bluetooth adapter

ishere=$(hciconfig |grep Type |cut -d ':' -f1)


# start blueman-applet if present

if [ "$ishere" = "" ]; then
	echo "No bluetooth"
	else
	echo "bluetooth found"
	blueman-applet &
fi

exit 0
