#!/bin/bash

#localize Thunar custom actions for available translations

#Pull locale info from F2 Live Boot Menu Setup

#LNG=$(cat /etc/default/locale|grep LANG|cut -d_ -f1|cut -d= -f2)
#echo $LNG

#this script can be run to bring updated uca.xml files into the user's home folder in the event of a system update
#this script will affect all user's Thunar configurations




localize_thunar_custom_actions()
{
#copy uca.xml file into appropriate location, use $LNG if exists, or uca_en (english) by default

  cp /etc/skel/.config/Thunar/uca.xml /home/*/.config/Thunar/uca.xml
  cp /etc/skel/.config/Thunar/uca.xml /root/.config/Thunar/uca.xml 

}

#look for a check file and if present exit, otherwise create check file and then parse language


main()
{

echo "localizing thunar custom actions"
if [ -e /etc/thunarCA_localize.chk ]; then
    rm /etc/thunarCA_localize.chk
fi

localize_thunar_custom_actions
}

main
