#! /bin/sh

set -e

if [ -e /etc/skel/.config/Thunar/uca.xml ]; then
    rm /etc/skel/.config/Thunar/uca.xml
fi

if [ -d /etc/skel/.config/Thunar ]; then
    cp /usr/share/desktop-defaults-mx/uca.xml /etc/skel/.config/Thunar/uca.xml
else
    mkdir -p /etc/skel/.config/Thunar
    cp /usr/share/desktop-defaults-mx/uca.xml /etc/skel/.config/Thunar/uca.xml
fi

if [ -e /root/.config/Thunar/uca.xml ]; then
    rm /root/.config/Thunar/uca.xml
fi

if [ -d /root/.config/Thunar ]; then
    cp /usr/share/desktop-defaults-mx/uca.xml /root/.config/Thunar/uca.xml
else
    mkdir -p /root/.config/Thunar
    cp /usr/share/desktop-defaults-mx/uca.xml /root/.config/Thunar/uca.xml  
fi

if [ ! -f /etc/X11/Xsession.d/98qtconfig  ]; then
    # do nothing no  98qtconfig found
    echo "98qtconfig not found...skipping..."
    :
elif sed -E '/^\s*$/d;/^\s*#.*$/d; 
          /\s*export\s+QT_QPA_PLATFORMTHEME=gtk2\s*$/d;
          /\s*export\s+QT_PLATFORMTHEME=gtk2\s*$/d;
          /\s*export\s+QT_PLATFORM_PLUGIN=gtk2\s*$/d;
          '  /etc/X11/Xsession.d/98qtconfig | grep -q . ; then 
    # do nothing
    # some changes found so we keep
    echo "98qtconfig customzations found...keeping"
    : 
else 
    # no content changes found so we can remove 
    rm /etc/X11/Xsession.d/98qtconfig
fi


exit 0
