#!/bin/sh

set -e

case "$1" in
  install|upgrade)
    grep -q QT_QPA_PLATFORMTHEME /etc/environment || echo 'QT_QPA_PLATFORMTHEME=gtk2'>>/etc/environment  
  ;;
  *)
    :
  ;;
esac

#DEBHELPER#

exit 0
